# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: score.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'score.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bscore.proto\x12\x05score\"\x1a\n\nJsonVector\x12\x0c\n\x04json\x18\x01 \x01(\t\"\x1e\n\rScoreResponse\x12\r\n\x05score\x18\x01 \x01(\x01\x32\x43\n\x0cScoreService\x12\x33\n\x08GetScore\x12\x11.score.JsonVector\x1a\x14.score.ScoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'score_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JSONVECTOR']._serialized_start=22
  _globals['_JSONVECTOR']._serialized_end=48
  _globals['_SCORERESPONSE']._serialized_start=50
  _globals['_SCORERESPONSE']._serialized_end=80
  _globals['_SCORESERVICE']._serialized_start=82
  _globals['_SCORESERVICE']._serialized_end=149
# @@protoc_insertion_point(module_scope)
